trigger:
  branches:
    include:
      - master

jobs:
- job: TestJob
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    # Instalar Node.js usando a task NodeTool
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
        addToPath: true

    # Instalar dependências do projeto
    - script: |
        npm install
      displayName: 'Install dependencies'

    # Executar o Cypress
    - script: |
        npx cypress run
      displayName: 'Run Cypress Tests'

    # Gerar relatórios com Mochawesome
    - script: |
        npx mochawesome-merge cypress/results/*.json > cypress/results/report.json
        npx mochawesome-report-generator cypress/results/report.json --reportDir=cypress/results
      displayName: 'Generate Mochawesome Report'
