trigger:
  branches:
    include:
      - master  # Altere para a branch que você deseja monitorar (ex: master ou main)
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14.x'  # Ou qualquer versão necessária
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npx cypress run --reporter mochawesome
  displayName: 'Run Cypress Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cypress/results'
    ArtifactName: 'TestResults'
    publishLocation: 'Container'
  displayName: 'Publish Test Results'
